### ISSUE TITLE
Testing Baxi with Remeha etwist

### ISSUE THREAD

**Issue by dacowiec** [vipial1/BAXI_thermostat#3]
Hi I am testing the Baxi thermostat in combination with Remeha eTwist thermostat. It is the same product but with a different name released on the Dutch market. It would be great if it is possible to make your integration work.

Unfortunately, when configuring the integration, I get the following error message.

Error setting up entry Baxi Thermostat for baxi_thermostat
14:45:04 – (FOUT) BAXI Thermostat (aangepaste integratie)
ERROR logging to BAXI. Perhaps wrong password??
14:45:04 – (FOUT) BAXI Thermostat (aangepaste integratie)
ERROR with post request to https://remoteapp.bdrthermea.com/user/baxi/login: 401
14:45:04 – (FOUT) BAXI Thermostat (aangepaste integratie)

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.baxi_thermostat.BaxiAPI
Source: custom_components/baxi_thermostat/BaxiAPI.py:108
Integration: BAXI Thermostat (documentation)
First occurred: 14:45:04 (1 occurrences)
Last logged: 14:45:04

ERROR with post request to https://remoteapp.bdrthermea.com/user/baxi/login: 401

The address vrequest address for etwist may be different at BDR Group. Who knows, we may find out.

The credentials I use to configure the integration are correct.

**Comment by vipial1** [comment]
Hello,
Probably it is a “generic” device and each brand can rebrand it as desired. If so, I would also bet that the API is completely designed by each company. But honestly, no idea.
I would like to help you but I don’t have that device so no access to the api. If you get the calls/urls, I will be happy to add it to the integration.
