### ISSUE TITLE
Only one entity?

### ISSUE THREAD

**Issue by davisdmg** [vipial1/BAXI_thermostat#4]
Hi!

I just installed your integration. Many thanks for your work!

I found out that only one entity was created (I used the UI):

![image](https://user-images.githubusercontent.com/63923271/170723055-d6ffe002-b34a-4a48-bfe1-cbc950d3a0f1.png)

![image](https://user-images.githubusercontent.com/63923271/170723102-54686745-3f65-4a81-ac8f-5b6fdd438677.png)

Am I doing something wrong?

**Comment by vipial1** [comment]
I see that you are using thermostat EHC-04…that is different to mine, so it is untested. Probably your thermostat doesn’t support consumption measurement…

**Comment by srodighiero** [comment]
Me too, I have a GTW-16 (that is what the integration sees) and a thermostat "RU2" (thi si what I can see/read on the "info" section of the Baxi App), here the log:

Logger: homeassistant.components.sensor
Source: custom_components/baxi_thermostat/BaxiAPI.py:237
Integration: Sensor (documentation, issues)
First occurred: 15:49:45 (2 occurrences)
Last logged: 15:49:45

baxi_thermostat: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 477, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
    await task
  File "/config/custom_components/baxi_thermostat/sensor.py", line 89, in async_update
    consumptions = await self._baxi_api.get_consumptions()
  File "/config/custom_components/baxi_thermostat/BaxiAPI.py", line 237, in get_consumptions
    api_endpoint = self.capabilities["producers"]["energyConsumptionUri"]
KeyError: 'energyConsumptionUri'
