### ISSUE TITLE
Can't find custom_components in HACS

### ISSUE THREAD

**Issue by alessandrobenevelli** [vipial1/BAXI_thermostat#5]
hi, in the installation instructions it says to download the custom_components from HACS but it's not there. Is a certain version of HACS required to download it or is it not present?
Thank you

**Comment by vipial1** [comment]
You need to add it as custom repository:
![2F17004A-5B14-4604-9448-5BBDA1A6A730](https://user-images.githubusercontent.com/4264467/183144646-65610dc2-b8d3-40a4-a60c-7d254b6528fe.jpeg)
